spring:
  datasource:
    url: jdbc:h2:mem:warehousedb
  h2:
    console:
      enabled: true
  jackson:
    deserialization:
      FAIL_ON_NULL_FOR_PRIMITIVES: true
      FAIL_ON_UNKNOWN_PROPERTIES: true
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB